import { createClient } from "https://esm.sh/@supabase/supabase-js@2.56.0";
import { corsHeaders } from "../_shared/cors.ts";
import { buildDocxFromText } from "../_shared/docx.ts";

function jsonResponse(status: number, body: Record<string, unknown>) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json",
    },
  });
}

function sanitizeBaseName(name: string) {
  const noExt = name.replace(/\.[^/.]+$/, "");
  const cleaned = noExt.replace(/[^a-zA-Z0-9._-]/g, "_").trim();
  return cleaned.length > 0 ? cleaned : "result";
}

function buildFallbackMarkdown(inputMeta: Array<Record<string, unknown>>) {
  const lines = [
    "# OCR Result",
    "",
    "This output was generated by worker fallback mode.",
    "",
    "## Input Files",
  ];
  for (const item of inputMeta) {
    const name = item.name?.toString() ?? "unknown.pdf";
    const size = item.size_mb?.toString() ?? "0";
    lines.push(`- ${name} (${size} MB)`);
  }
  lines.push("");
  lines.push("## Extracted Text");
  lines.push("Sample placeholder text. Connect LIGHTON_OCR_ENDPOINT for real OCR.");
  return lines.join("\n");
}

function asObject(value: unknown): Record<string, unknown> | null {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return null;
  }
  return value as Record<string, unknown>;
}

function toNonEmptyString(value: unknown): string | null {
  if (typeof value === "string") {
    const trimmed = value.trim();
    return trimmed.length > 0 ? trimmed : null;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  return null;
}

function getByPath(root: unknown, path: Array<string | number>): unknown {
  let current: unknown = root;
  for (const part of path) {
    if (typeof part === "number") {
      if (!Array.isArray(current) || part < 0 || part >= current.length) {
        return undefined;
      }
      current = current[part];
      continue;
    }
    const objectValue = asObject(current);
    if (!objectValue || !(part in objectValue)) {
      return undefined;
    }
    current = objectValue[part];
  }
  return current;
}

function extractTextNodes(value: unknown, depth = 0): string[] {
  if (depth > 8) return [];

  const scalar = toNonEmptyString(value);
  if (scalar) return [scalar];

  if (Array.isArray(value)) {
    return value.flatMap((item) => extractTextNodes(item, depth + 1));
  }

  const objectValue = asObject(value);
  if (!objectValue) return [];

  const preferredKeys = [
    "markdown",
    "text",
    "content",
    "output_text",
    "output",
    "value",
  ];
  const wrapperKeys = [
    "result",
    "results",
    "response",
    "responses",
    "data",
    "message",
    "messages",
    "choice",
    "choices",
    "prediction",
    "predictions",
    "candidate",
    "candidates",
    "page",
    "pages",
    "item",
    "items",
    "part",
    "parts",
    "outputs",
    "generated",
  ];

  const out: string[] = [];
  for (const key of preferredKeys) {
    if (key in objectValue) {
      out.push(...extractTextNodes(objectValue[key], depth + 1));
    }
  }
  for (const key of wrapperKeys) {
    if (key in objectValue) {
      out.push(...extractTextNodes(objectValue[key], depth + 1));
    }
  }

  if (out.length > 0) return out;

  const textishEntries = Object.entries(objectValue).filter(([key]) =>
    /text|markdown|content|output|ocr|transcript|value/i.test(key),
  );
  if (textishEntries.length === 0) return [];
  return textishEntries.flatMap(([, nested]) =>
    extractTextNodes(nested, depth + 1),
  );
}

function extractLightOnText(data: unknown): string | null {
  const explicitPaths: Array<Array<string | number>> = [
    ["markdown"],
    ["text"],
    ["content"],
    ["output"],
    ["result", "markdown"],
    ["result", "text"],
    ["result", "content"],
    ["response", "markdown"],
    ["response", "text"],
    ["response", "content"],
    ["data", "markdown"],
    ["data", "text"],
    ["data", "content"],
    ["choices", 0, "message", "content"],
    ["choices", 0, "text"],
    ["choices", 0, "message", "output_text"],
    ["outputs", 0, "text"],
    ["outputs", 0, "content"],
    ["predictions", 0, "text"],
    ["candidates", 0, "content", "parts"],
    ["pages"],
  ];

  for (const path of explicitPaths) {
    const candidate = getByPath(data, path);
    const texts = extractTextNodes(candidate);
    if (texts.length > 0) {
      const deduped = [...new Set(texts.map((v) => v.trim()).filter(Boolean))];
      if (deduped.length > 0) return deduped.join("\n\n");
    }
  }

  const fallback = extractTextNodes(data);
  if (fallback.length === 0) return null;
  const deduped = [...new Set(fallback.map((v) => v.trim()).filter(Boolean))];
  return deduped.length > 0 ? deduped.join("\n\n") : null;
}

async function callLightOn(
  endpoint: string,
  token: string,
  inputMeta: Array<Record<string, unknown>>,
) {
  const payload = {
    inputs: {
      prompt: "Extract text from provided document pages.",
      files: inputMeta,
    },
  };
  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });
  if (!response.ok) {
    throw new Error(`lighton_http_${response.status}`);
  }
  const rawText = await response.text();
  let data: unknown = rawText;
  try {
    data = JSON.parse(rawText);
  } catch {
    // Keep plain text response as-is.
  }

  const extracted = extractLightOnText(data);
  if (extracted) return extracted;

  const scalar = toNonEmptyString(data);
  if (scalar) return scalar;

  return typeof rawText === "string" && rawText.trim().length > 0
    ? rawText
    : JSON.stringify(data);
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  if (req.method !== "POST") {
    return jsonResponse(405, { error: "method_not_allowed" });
  }

  try {
    const expectedSecret = Deno.env.get("OCR_WORKER_SECRET") ?? "";
    if (expectedSecret) {
      const auth = req.headers.get("Authorization") ?? "";
      const token = auth.replace("Bearer ", "").trim();
      if (!token || token !== expectedSecret) {
        return jsonResponse(401, { error: "invalid_worker_secret" });
      }
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
    if (!supabaseUrl || !serviceRoleKey) {
      return jsonResponse(500, { error: "missing_supabase_env" });
    }
    const admin = createClient(supabaseUrl, serviceRoleKey);

    const body = (await req.json().catch(() => ({}))) as { job_id?: string };
    const jobId = body.job_id?.toString().trim();
    if (!jobId) {
      return jsonResponse(400, { error: "job_id_required" });
    }

    const rowRes = await admin
      .from("ocr_jobs")
      .select("id, input_meta")
      .eq("id", jobId)
      .maybeSingle();

    if (rowRes.error) {
      return jsonResponse(500, {
        error: "job_query_failed",
        detail: rowRes.error.message,
      });
    }
    if (!rowRes.data) {
      return jsonResponse(404, { error: "job_not_found" });
    }

    const inputMeta = Array.isArray(rowRes.data.input_meta)
      ? rowRes.data.input_meta
      : [];
    const firstName = inputMeta[0]?.name?.toString() ?? "result.pdf";
    const baseName = sanitizeBaseName(firstName);

    await admin
      .from("ocr_jobs")
      .update({
        status: "processing",
        progress_pct: 60,
      })
      .eq("id", jobId);

    const lightOnEndpoint = Deno.env.get("LIGHTON_OCR_ENDPOINT") ?? "";
    const lightOnToken = Deno.env.get("LIGHTON_OCR_TOKEN") ?? "";
    const markdown =
      lightOnEndpoint && lightOnToken
        ? await callLightOn(lightOnEndpoint, lightOnToken, inputMeta)
        : buildFallbackMarkdown(inputMeta);

    const outputBucket = Deno.env.get("OCR_RESULTS_BUCKET") ?? "ocr-results";
    const mdPath = `${jobId}/output/${baseName}.md`;
    const docxPath = `${jobId}/output/${baseName}.docx`;

    const mdUpload = await admin.storage
      .from(outputBucket)
      .upload(mdPath, new TextEncoder().encode(markdown), {
        contentType: "text/markdown",
        upsert: true,
      });

    if (mdUpload.error) {
      throw new Error(`md_upload_failed:${mdUpload.error.message}`);
    }

    const docxUpload = await admin.storage
      .from(outputBucket)
      .upload(docxPath, buildDocxFromText(markdown), {
        contentType:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        upsert: true,
      });

    if (docxUpload.error) {
      throw new Error(`docx_upload_failed:${docxUpload.error.message}`);
    }

    await admin
      .from("ocr_jobs")
      .update({
        status: "succeeded",
        progress_pct: 100,
        output_md_path: mdPath,
        output_docx_path: docxPath,
        finished_at: new Date().toISOString(),
      })
      .eq("id", jobId);

    return jsonResponse(200, {
      job_id: jobId,
      status: "succeeded",
      output_md_path: mdPath,
      output_docx_path: docxPath,
    });
  } catch (error) {
    const detail = error instanceof Error ? error.message : "unknown";
    return jsonResponse(500, { error: "unexpected_error", detail });
  }
});
